#!/usr/bin/env bash
# One-time developer setup: venv + live proxy + Claude Code wiring.
#
# Usage:
#   bash run-setup.sh firstname.lastname
#   bash install.sh firstname.lastname
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_DEFAULT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/context-synthesizer"
CONFIG_FILE="$CONFIG_DIR/developer.env"

DEVELOPER=""
ENABLE_PROXY=0
EXPORT_MODE="d"
CURSOR_PROJECT=""
API_KEY=""
INSTALL_DIR=""
REPO_ROOT=""

usage() {
  sed -n '2,6p' "$0" | sed 's/^# \{0,1\}//'
  echo "  --install-dir PATH   Toolkit root (default: package root)"
  exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --developer) DEVELOPER="$2"; shift 2 ;;
    --enable-proxy) ENABLE_PROXY=1; shift ;;
    --export-mode) EXPORT_MODE="$2"; shift 2 ;;
    --cursor-project) CURSOR_PROJECT="$2"; shift 2 ;;
    --api-key) API_KEY="$2"; shift 2 ;;
    --install-dir) INSTALL_DIR="$2"; shift 2 ;;
    -h|--help) usage 0 ;;
    *)
      if [[ -z "$DEVELOPER" && "$1" != -* ]]; then
        DEVELOPER="$1"
        shift
      else
        echo "Unknown option: $1" >&2
        usage 1
      fi
      ;;
  esac
done

if [[ -z "$DEVELOPER" ]]; then
  echo "Required: firstname.lastname (e.g. harshil.shah)" >&2
  usage 1
fi

REPO_ROOT="${INSTALL_DIR:-$_DEFAULT_ROOT}"
export REPO_ROOT

check_systemd_user() {
  if ! command -v systemctl >/dev/null 2>&1; then
    echo "ERROR: systemctl not found — live proxy requires systemd user services." >&2
    exit 1
  fi
  if ! systemctl --user show-environment >/dev/null 2>&1; then
    echo "" >&2
    echo "ERROR: systemd user session is not available." >&2
    if [[ -f /proc/version ]] && grep -qi microsoft /proc/version; then
      echo "  WSL: [boot] systemd=true in /etc/wsl.conf, then wsl --shutdown" >&2
    else
      echo "  Ubuntu: loginctl enable-linger \$USER" >&2
    fi
    exit 1
  fi
}

echo "=== Context Synthesizer — developer setup ==="
bash "$SCRIPT_DIR/setup.sh"

mkdir -p "$CONFIG_DIR"
{
  echo "# Generated by setup_developer.sh — do not commit"
  printf 'TELEMETRY_DEVELOPER_ID=%q\n' "$DEVELOPER"
  printf 'REPO_ROOT=%q\n' "$REPO_ROOT"
  printf 'EXPORT_MODE=%q\n' "$EXPORT_MODE"
  printf 'ENABLE_PROXY=%q\n' "$ENABLE_PROXY"
  [[ -n "$CURSOR_PROJECT" ]] && printf 'CURSOR_PROJECT=%q\n' "$CURSOR_PROJECT"
} >"$CONFIG_FILE"
chmod 600 "$CONFIG_FILE"
echo "Wrote $CONFIG_FILE"

if [[ "$ENABLE_PROXY" -eq 1 ]]; then
  check_systemd_user
  ENV_FILE="$REPO_ROOT/context-synthesizer/.env"
  if [[ -n "$API_KEY" ]]; then
    grep -q '^ANTHROPIC_API_KEY=' "$ENV_FILE" 2>/dev/null || echo "ANTHROPIC_API_KEY=${API_KEY}" >>"$ENV_FILE"
    chmod 600 "$ENV_FILE" 2>/dev/null || true
  fi
  _port_free() {
    local p="$1"
    "$REPO_ROOT/.venv/bin/python" -c "
import socket, sys
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
try:
    s.bind(('127.0.0.1', int(sys.argv[1])))
except OSError:
    sys.exit(1)
finally:
    s.close()
" "$p" 2>/dev/null
  }
  _current_port() {
    if [[ -f "$ENV_FILE" ]]; then
      grep -E '^PROXY_PORT=' "$ENV_FILE" 2>/dev/null | tail -1 | cut -d= -f2
    fi
  }
  PROXY_PORT="$(_current_port)"
  PROXY_PORT="${PROXY_PORT:-8080}"
  if ! _port_free "$PROXY_PORT"; then
    if [[ "$PROXY_PORT" == "8080" ]] && _port_free 8081; then
      if grep -q '^PROXY_PORT=' "$ENV_FILE" 2>/dev/null; then
        sed -i 's/^PROXY_PORT=.*/PROXY_PORT=8081/' "$ENV_FILE"
      else
        echo 'PROXY_PORT=8081' >>"$ENV_FILE"
      fi
      PROXY_PORT=8081
      echo "Port 8080 busy → PROXY_PORT=8081"
    else
      echo "WARNING: port $PROXY_PORT in use — set PROXY_PORT in $ENV_FILE" >&2
    fi
  fi
  if [[ -f /proc/version ]] && grep -qi microsoft /proc/version; then
    if ! grep -q '^PROXY_HOST=' "$ENV_FILE" 2>/dev/null; then
      echo 'PROXY_HOST=0.0.0.0' >>"$ENV_FILE"
    fi
    if ! grep -q '^DASHBOARD_TOKEN=' "$ENV_FILE" 2>/dev/null; then
      DASH_TOKEN="$(openssl rand -hex 16 2>/dev/null || tr -dc 'a-f0-9' </dev/urandom | head -c 32)"
      echo "DASHBOARD_TOKEN=${DASH_TOKEN}" >>"$ENV_FILE"
    fi
  fi
  bash "$SCRIPT_DIR/configure_claude_proxy.sh"
  bash "$SCRIPT_DIR/install_proxy_service.sh"
  echo ""
  echo "Live compaction: ON — use Claude Code (Max/Pro login, no API key)."
fi

echo ""
echo "=== Setup complete ==="
echo "Developer ID: $DEVELOPER"
echo "  Live compaction: $([[ "$ENABLE_PROXY" -eq 1 ]] && echo ON || echo OFF)"
echo ""
echo "  csynth status | csynth dashboard | csynth doctor"
echo "  csynth proxy on | csynth proxy off"
echo ""
if [[ "$ENABLE_PROXY" -eq 1 ]]; then
  echo "Smoke test:"
  echo "  systemctl --user status context-synthesizer-proxy"
fi
echo "Install location: ${REPO_ROOT}"

BIN_DIR="${HOME}/.local/bin"
mkdir -p "$BIN_DIR"
install -m 755 "$SCRIPT_DIR/csynth" "$BIN_DIR/csynth"
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
  echo ""
  echo "Add to PATH (once): export PATH=\"\$HOME/.local/bin:\$PATH\""
fi
