#!/usr/bin/env bash
# One-time developer setup: venv + config + optional proxy + weekly cron + drive upload.
#
# Usage:
#   curl -fsSL <install.sh-url> | bash -s -- --developer YOU --rclone-remote 'gdrive:...' --enable-proxy --install-cron
#   bash install.sh --developer YOU ...   (same — install.sh delegates here)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_DEFAULT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/context-synthesizer"
CONFIG_FILE="$CONFIG_DIR/developer.env"

DEVELOPER=""
RCLONE_REMOTE=""
SYNC_DIR=""
ENABLE_PROXY=0
INSTALL_CRON=0
EXPORT_MODE="d"
CURSOR_PROJECT=""
API_KEY=""
INSTALL_DIR=""
REPO_ROOT=""

usage() {
  sed -n '2,8p' "$0" | sed 's/^# \{0,1\}//'
  echo "  --install-dir PATH   Toolkit root (default: repo root or ~/.local/share/context-synthesizer)"
  exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --developer) DEVELOPER="$2"; shift 2 ;;
    --rclone-remote) RCLONE_REMOTE="$2"; shift 2 ;;
    --sync-dir) SYNC_DIR="$2"; shift 2 ;;
    --enable-proxy) ENABLE_PROXY=1; shift ;;
    --install-cron) INSTALL_CRON=1; shift ;;
    --export-mode) EXPORT_MODE="$2"; shift 2 ;;
    --cursor-project) CURSOR_PROJECT="$2"; shift 2 ;;
    --api-key) API_KEY="$2"; shift 2 ;;
    --install-dir) INSTALL_DIR="$2"; shift 2 ;;
    -h|--help) usage 0 ;;
    *) echo "Unknown option: $1" >&2; usage 1 ;;
  esac
done

if [[ -z "$DEVELOPER" ]]; then
  echo "Required: --developer YOUR_ID (e.g. azure email local-part: firstname.lastname)" >&2
  usage 1
fi

if [[ "$INSTALL_CRON" -eq 1 ]] && [[ -z "$RCLONE_REMOTE" ]] && [[ -z "$SYNC_DIR" ]]; then
  echo "Weekly cron needs an upload target: --sync-dir (OneDrive) or --rclone-remote" >&2
  exit 1
fi

REPO_ROOT="${INSTALL_DIR:-$_DEFAULT_ROOT}"
export REPO_ROOT

echo "=== Context Synthesizer — developer setup ==="
bash "$SCRIPT_DIR/setup.sh"

mkdir -p "$CONFIG_DIR"
{
  echo "# Generated by setup_developer.sh — do not commit"
  printf 'TELEMETRY_DEVELOPER_ID=%q\n' "$DEVELOPER"
  printf 'REPO_ROOT=%q\n' "$REPO_ROOT"
  printf 'EXPORT_MODE=%q\n' "$EXPORT_MODE"
  printf 'RCLONE_REMOTE=%q\n' "$RCLONE_REMOTE"
  printf 'SYNC_DIR=%q\n' "$SYNC_DIR"
  printf 'ENABLE_PROXY=%q\n' "$ENABLE_PROXY"
  echo "CRON_HOUR=9"
  echo "CRON_DOW=1"
  [[ -n "$CURSOR_PROJECT" ]] && printf 'CURSOR_PROJECT=%q\n' "$CURSOR_PROJECT"
} >"$CONFIG_FILE"
chmod 600 "$CONFIG_FILE"
echo "Wrote $CONFIG_FILE"

if [[ "$ENABLE_PROXY" -eq 1 ]]; then
  ENV_FILE="$REPO_ROOT/context-synthesizer/.env"
  if [[ -n "$API_KEY" ]]; then
    grep -q '^ANTHROPIC_API_KEY=' "$ENV_FILE" 2>/dev/null || echo "ANTHROPIC_API_KEY=${API_KEY}" >>"$ENV_FILE"
  elif [[ ! -f "$ENV_FILE" ]] || ! grep -q '^ANTHROPIC_API_KEY=' "$ENV_FILE" 2>/dev/null; then
    echo ""
    echo "Proxy needs ANTHROPIC_API_KEY (Claude API / Max BYOK for local gateway)."
    read -r -s -p "Paste API key (hidden): " API_KEY
    echo ""
    echo "ANTHROPIC_API_KEY=${API_KEY}" >>"$ENV_FILE"
  fi
  chmod 600 "$ENV_FILE" 2>/dev/null || true
  bash "$SCRIPT_DIR/configure_claude_proxy.sh"
  bash "$SCRIPT_DIR/install_proxy_service.sh"
  echo ""
  echo "Live benefit: use Claude Code normally — traffic routes through synthesizer proxy."
fi

if [[ -n "$SYNC_DIR" ]]; then
  mkdir -p "$SYNC_DIR"
  echo "Weekly files copy → $SYNC_DIR (OneDrive syncs to SharePoint)"
elif [[ -n "$RCLONE_REMOTE" ]]; then
  if ! command -v rclone >/dev/null 2>&1; then
    echo ""
    echo "Install rclone for auto-upload: https://rclone.org/install/"
    echo "Or re-run with --sync-dir for OneDrive folder instead."
  fi
fi

if [[ "$INSTALL_CRON" -eq 1 ]]; then
  bash "$SCRIPT_DIR/install_weekly_cron.sh"
  echo "Weekly auto-export + upload scheduled (Mondays 09:00)."
fi

echo ""
echo "=== Setup complete ==="
echo "Developer ID: $DEVELOPER"
if [[ "$ENABLE_PROXY" -eq 1 ]]; then
  echo "  Live compaction: ON (proxy user service)"
else
  echo "  Live compaction: OFF (add --enable-proxy to activate)"
fi
if [[ -n "$SYNC_DIR" ]]; then
  echo "  OneDrive sync: $SYNC_DIR"
elif [[ -n "$RCLONE_REMOTE" ]]; then
  echo "  Shared drive:  $RCLONE_REMOTE"
fi
if [[ "$INSTALL_CRON" -eq 1 ]]; then
  echo "  Weekly cron:   ON"
else
  echo "  Weekly cron:   OFF (add --install-cron or run weekly_sync.sh manually)"
fi
echo ""
echo "Smoke test:"
echo "  bash ${REPO_ROOT}/context-synthesizer/scripts/weekly_sync.sh"
echo "Install location: ${REPO_ROOT}"
